### ISSUE TITLE
Data Missing in Prepare MSCOCO data and Inception model

### ISSUE THREAD

**Issue by navneetkrc** [zsdonghao/Image-Captioning#1]
These links are not working.
Download and Preprocessing MSCOCO Data click here
Download the Inception_V3 CKPT click here.

Please check

**Comment by KyrieHee** [comment]
**MSCOCO Data**   http://cocodataset.org/
**Inception_V3 CKPT**  https://github.com/tensorflow/models/tree/master/research/slim#tensorflow-slim-image-classification-library
